// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "admindashboard-20200312193453-hostingbucket-adminclien",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://admindashboard-20200312193453-hostingbucket-adminclien.s3-website-us-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-west-2:7c3e2cbb-3c5e-45fa-9deb-9bfef0ae93fc",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_oFAuIHKYa",
    "aws_user_pools_web_client_id": "en8k7ok5ehgul7rsogq3rllbb",
    "oauth": {}
};


export default awsmobile;
